// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using psigestor.Data;

#nullable disable

namespace psigestor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250704001721_AddQuestionnaireColumns")]
    partial class AddQuestionnaireColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("psigestor.Data.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AnswerValue")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("psigestor.Data.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Question1")
                        .HasColumnType("int");

                    b.Property<int>("Question10")
                        .HasColumnType("int");

                    b.Property<int>("Question11")
                        .HasColumnType("int");

                    b.Property<int>("Question12")
                        .HasColumnType("int");

                    b.Property<int>("Question13")
                        .HasColumnType("int");

                    b.Property<int>("Question14")
                        .HasColumnType("int");

                    b.Property<int>("Question15")
                        .HasColumnType("int");

                    b.Property<int>("Question16")
                        .HasColumnType("int");

                    b.Property<int>("Question17")
                        .HasColumnType("int");

                    b.Property<int>("Question18")
                        .HasColumnType("int");

                    b.Property<int>("Question19")
                        .HasColumnType("int");

                    b.Property<int>("Question2")
                        .HasColumnType("int");

                    b.Property<int>("Question20")
                        .HasColumnType("int");

                    b.Property<int>("Question3")
                        .HasColumnType("int");

                    b.Property<int>("Question4")
                        .HasColumnType("int");

                    b.Property<int>("Question5")
                        .HasColumnType("int");

                    b.Property<int>("Question6")
                        .HasColumnType("int");

                    b.Property<int>("Question7")
                        .HasColumnType("int");

                    b.Property<int>("Question8")
                        .HasColumnType("int");

                    b.Property<int>("Question9")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SufferingLevel")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("psigestor.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("psigestor.Data.Answer", b =>
                {
                    b.HasOne("psigestor.Data.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("psigestor.Data.Questionnaire", b =>
                {
                    b.HasOne("psigestor.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
